### ISSUE TITLE
Column indexing

### ISSUE THREAD

**Issue by femtotrader** [xKDR/TimeFrames.jl#116]
Hello,

Currently column indexing doesn't seems to work (at least not like I was expecting)

```julia
julia> using TimeFrames, MarketData;
julia> ts=TimeFrame(MarketData.yahoo(:AAPL))
julia> ts[!, :Close]
ERROR: MethodError: no method matching getindex(::TimeFrame, ::typeof(!), ::Symbol)
Closest candidates are:
  getindex(::TimeFrame, ::UnitRange, ::Union{String, Symbol}) at C:\Users\femto\.julia\packages\TimeFrames\mMgMC\src\getindex.jl:374
  getindex(::TimeFrame, ::T, ::Union{String, Symbol}) where T<:TimeType at C:\Users\femto\.julia\packages\TimeFrames\mMgMC\src\getindex.jl:277
  getindex(::TimeFrame, ::AbstractVector{Int64}, ::Union{String, Symbol}) at C:\Users\femto\.julia\packages\TimeFrames\mMgMC\src\getindex.jl:314
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[26]:1
```

It seems that 

    TimeFrame(ts.coredata[!, [:Index, :Close]])

is a workaround

Selecting several columns should also be considered like this

    ts[!, [:Open, :Close]]

Kind regards

**Comment by femtotrader** [comment]
ts[:, [:Close]]

and

     ts[:, [:Open, :Close]]

does column indexing. Sorry for noise. Maybe it should be added to doc.

**Comment by chiraganand** [comment]
> ```
>  ts[:, [:Close]]
> ```
> 
> and
> 
> ```
>  ts[:, [:Open, :Close]]
> ```
> 
> does column indexing. Sorry for noise. Maybe it should be added to doc.

For some reason `getindex()` documentation isn't getting generated. Will check this.

**Comment by chiraganand** [comment]
> For some reason getindex() documentation isn't getting generated. Will check this.

Removed some unnecessary code from the top of `src/getindex.jl` which I thought could be causing this but the issue remains. @codetalker7 @ayushpatnaikgit  Any idea what could be causing getindex.jl documentation to get excluded by Documenter?
