### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by ViralBShah** [xKDR/TimeFrames.jl#66]
This package probably needs to be renamed if at some point it will be registered. I am quite certain that 3 letter package names are discouraged in the General registry.

https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines

**Comment by chiraganand** [comment]
Yes, the name will need to be changed before registering. Not sure if `SimpleTimeSeries` would be a better name, though, the essence has been to make handling time series data simpler.

**Comment by ViralBShah** [comment]
TSx is actually a good name but a 3 letter name won't fly. SimpleTimeSeries feels too generic.

**Comment by ParadaCarleton** [comment]
Given the package is essentially DataFrames for time series, what about `TimeFrames`?

**Comment by ViralBShah** [comment]
I like that

**Comment by chiraganand** [comment]
> Given the package is essentially DataFrames for time series, what about `TimeFrames`?

Yes, sounds good.

**Comment by ViralBShah** [comment]
Maybe execute the name change now if everyone is ok with it? Also, what's the plan to register these packages? Are we waiting on a particular set of capabilities before registering?

**Comment by chiraganand** [comment]
> Maybe execute the name change now if everyone is ok with it?

Yes, this should be done sooner than later because this will require code changes as well. I am assuming if `TimeFrames` is the package name then the data structure should be `TimeFrame` according to convention.

> Also, what's the plan to register these packages? Are we waiting on a particular set of capabilities before registering?

Yes, waiting for 3-4 core capabilities (some important rewrites and fixes) before releasing v0.1.0.

**Comment by ViralBShah** [comment]
Not strictly required, but yes, it is a good idea to use TimeFrame as the data structure name too.

**Comment by chiraganand** [comment]
@codetalker7 `docs/src/assets/sample_daily.csv` needs to be removed.

**Comment by chiraganand** [comment]
TimeFrames.jl is already registered so we need to come up with a new name. Names which already exist:
* TimeSeries
* TimeFrames
* TimeDataFrames
* TimeSeriesInterface

I suggest `TimedTables`, `TimeDF`, or just `TimeStruct`.

**Comment by ViralBShah** [comment]
@femtotrader, Would it be ok if we can take over the TimeFrames.jl package name from you? Mainly for the purposes of registering it in the Julia registry?

@kristofferC Would it be ok to do that? Or do you prefer we use a new name?

I think TimedTables and TimeDF are both fine.

**Comment by femtotrader** [comment]
I'm ok for giving the [TimeFrames.jl](https://github.com/femtotrader/TimeFrames.jl) package name... but the purpose of this package is very different... it's used by [TimeSeriesResampler](https://github.com/femtotrader/TimeSeriesResampler.jl) to provide an easy interface to resample timeseries from [TimeSeries.jl](https://juliastats.org/TimeSeries.jl/stable/).
What about naming your package `TimeSeriesFrames` ?

**Comment by KristofferC** [comment]
Easiest would be to find a new name. It might be possible in a roundabout way to "take over" the name but coming up with a slightly different name if possible would be to prefer for sure.

**Comment by ViralBShah** [comment]
Ok agree with everyone. A new name would be better.

**Comment by ParadaCarleton** [comment]
TimeTables.jl sounds good to me.

**Comment by ViralBShah** [comment]
Calling it `TimeTables.jl` would be confusing - I would think it is a package that generates a school or a railway time table. For that same reason `TimedTables` is not a great name either.

**Comment by chiraganand** [comment]
> Calling it `TimeTables.jl` would be confusing - I would think it is a package that generates a school or a railway time table. For that same reason `TimedTables` is not a great name either.
> 
> How about `TSFrames`?

Yes, this could work.
